services:
  app:
    image: oven/bun:alpine
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: sh -c "bun install && bun generate && bun dev"
    # command: "/bin/sh -c 'bun install && bunx prisma generate && bun run --watch src/main.ts'"
    volumes:
      - ./:/home/bun/app
    deploy:
      resources:
        limits:
          memory: 512MB

  postgres:
    image: postgres:17.4
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simple_stock
    volumes:
      - ./data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512MB

  